version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  automerge: true
  commit-message:
    prefix: "[dependabot][automerge]"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  automerge: true
  commit-message:
    prefix: "[github-actions][dependabot][automerge]"
  open-pull-requests-limit: 10
