name: Auto approve and merge Dependabot

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  auto-approve-and-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request
        uses: hmarr/auto-approve-action@v4.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Merge pull request
        uses: actions/github-script@v4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const pr = context.payload.pull_request
            const repo = context.repo
            await github.rest.pulls.merge({
              owner: repo.owner,
              repo: repo.repo,
              pull_number: pr.number
            })
